version: '3'
services:
  app:
    image: docker.te-k8s.com/wl/hyperf-energy-bot:latest
    container_name: ext-tron
    volumes:
      - ./:/data/project
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    working_dir: /data/project
    stdin_open: true
    tty: true


